chore: Export `BASE_DIR` environment variable
New users to `asdf` who wish to contribute will run into the following
errors when running `./scripts/test.bash`:

```
 ✗ help should show dummy plugin help specific to version when version is present [7]
   (from function `setup_asdf_dir' in file test/test_helpers.bash, line 16,
    from function `setup' in test file test/help_command.bats, line 6)
     `setup_asdf_dir' failed
   mkdir: cannot create directory ‘/w spacetest_help_should_show_dummy_plugin_help_specific_to_version_when_version_is_present’: Permission denied
```

This is due to paths within the various test suites relying on the
`BASE_DIR` environment variable, which is not set by default.

This pull request modifies `scripts/test.bash` to correctly export
`BASE_DIR`

Note: I am a long-time asdf user, who would like to contribute to the
project and noticed this while setting up my dev environment on an
up-to-date Arch Linux system. My intention is to work on this issue:

https://github.com/asdf-vm/asdf/issues/2042

Add `PATH` to variables exported to `bats`, because the use of `Env` requires providing *all* necessary env vars.

Otherwise, this is the result of running `make test`:

$ make test
go test -coverprofile=/tmp/coverage.out  -bench= -race ./...
--- FAIL: TestBatsTests (0.48s)
    --- FAIL: TestBatsTests/current_command (0.01s)
        main_test.go:23: stdout:
        main_test.go:23: stderr: error loading config: exec: "getent": executable file not found in $PATH